# GitHub Pages 配置
title: "數學英雄冒險"
description: "兒童數學教育遊戲，包含蜘蛛俠、鋼鐵人、黑豹關卡"
url: "https://sorosyeung-netizen.github.io"
baseurl: "/math-hero-adventure"

# 構建配置
markdown: kramdown
highlighter: rouge

# 包含的文件
include:
  - "數學英雄冒險.html"
  - "index.html"

# 排除的文件
exclude:
  - "*.py"
  - "Lib/"
  - "Include/"
  - "Scripts/"
  - "*.exe"
  - "upload-to-github.bat"

# 啟用GitHub Pages
plugins:
  - jekyll-feed
title: "Math Hero Adventure - 數學英雄冒險"
description: "一個有趣的數學教育遊戲，包含蜘蛛俠、鋼鐵人、黑豹等角色的關卡"
url: "https://YOUR_USERNAME.github.io"
baseurl: "/math-hero-adventure"

# 構建配置
markdown: kramdown
highlighter: rouge
permalink: pretty

# 排除檔案
exclude:
  - upload-to-github.bat
  - sounds/音效說明.txt
  - Lib/
  - Include/
  - Scripts/

# 預設佈局
defaults:
  - scope:
      path: ""
    values:
      layout: default